

SELECT T.AUTHORID,T."TOTAL_COMM"+K."TOTAL_POST"
FROM (
  SELECT f.AUTHORID,SUM(Z."COUNT_OF_COMM_LIKES") AS "TOTAL_COMM"
FROM fbcomment f,
(
 SELECT LC.COMMENT_ID,COUNT(LC.COMMENT_ID) AS "COUNT_OF_COMM_LIKES"
FROM likecomment LC
GROUP BY LC.COMMENT_ID
) Z
WHERE f.COMMENTID = Z.COMMENT_ID
GROUP BY f.AUTHORID
ORDER BY SUM(Z."COUNT_OF_COMM_LIKES") DESC
) T,
(
 SELECT p.AUTHOR,SUM(Q."COUNT_OF_POST_LIKES") AS "TOTAL_POST"
FROM POST p,
(
SELECT LP.POST_ID,COUNT(LP.POST_ID) AS "COUNT_OF_POST_LIKES"
FROM likepost LP
GROUP BY LP.POST_ID
) Q
WHERE p.POSTID = Q.POST_ID
GROUP BY p.AUTHOR
ORDER BY SUM(Q."COUNT_OF_POST_LIKES") DESC
) K
WHERE T.AUTHORID = K.AUTHOR AND ROWNUM < 3
ORDER BY (T."TOTAL_COMM"+K."TOTAL_POST") DESC;
